presets:
  custom:
    name: "StandardPush"
    description: "8am and 8pm push"
    default:
      collect: true
      analyze: false
      push: false
      report_mode: "current"
      once:
        push: true
    periods:
      morning_8am:
        name: "Morning"
        start: "08:00"
        end: "08:30"
        push: true
      evening_8pm:
        name: "Evening"
        start: "20:00"
        end: "20:30"
        push: true
    day_plans:
      daily_plan:
        periods: ["morning_8am", "evening_8pm"]
    week_map:
      1: "daily_plan"
      2: "daily_plan"
      3: "daily_plan"
      4: "daily_plan"
      5: "daily_plan"
      6: "daily_plan"
      7: "daily_plan"
